# Generated by Django 5.2.3 on 2025-07-03 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubtipoGlosa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoGlosa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoGlosaRespuestaIPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubCodigoGlosa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=255)),
                ('subtipo_glosa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcodigos', to='auditoria.subtipoglosa')),
            ],
            options={
                'unique_together': {('subtipo_glosa', 'codigo')},
            },
        ),
        migrations.AddField(
            model_name='subtipoglosa',
            name='tipo_glosa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtipos', to='auditoria.tipoglosa'),
        ),
        migrations.CreateModel(
            name='SubtipoGlosaRespuestaIPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_glosa_respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtipos_respuesta', to='auditoria.tipoglosarespuestaips')),
            ],
        ),
        migrations.CreateModel(
            name='Glosa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('valor_glosado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
                ('fecha_glosa', models.DateField(auto_now_add=True)),
                ('descripcion_respuesta', models.TextField(blank=True, null=True)),
                ('archivo_soporte_respuesta', models.FileField(blank=True, null=True, upload_to='respuestas_glosas/')),
                ('aceptada', models.BooleanField(blank=True, null=True)),
                ('fecha_respuesta', models.DateField(blank=True, null=True)),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='glosas', to='facturacion.ripsconsulta')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glosas', to='facturacion.factura')),
                ('hospitalizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='glosas', to='facturacion.ripshospitalizacion')),
                ('medicamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='glosas', to='facturacion.ripsmedicamento')),
                ('otro_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='glosas', to='facturacion.ripsotroservicio')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.paciente')),
                ('procedimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='glosas', to='facturacion.ripsprocedimiento')),
                ('subcodigo_glosa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auditoria.subcodigoglosa')),
                ('subtipo_glosa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auditoria.subtipoglosa')),
                ('subtipo_glosa_respuesta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auditoria.subtipoglosarespuestaips')),
                ('tipo_glosa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auditoria.tipoglosa')),
                ('tipo_glosa_respuesta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auditoria.tipoglosarespuestaips')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='subtipoglosa',
            unique_together={('tipo_glosa', 'codigo')},
        ),
    ]
