# Generated by Django 5.2.3 on 2025-06-24 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glosa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_glosa', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('valor_glosado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
                ('respuesta', models.TextField(blank=True)),
                ('aceptada', models.BooleanField(blank=True, null=True)),
                ('fecha_glosa', models.DateField(auto_now_add=True)),
                ('fecha_respuesta', models.DateField(blank=True, null=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.factura')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.ripsitem')),
            ],
        ),
    ]
