# Generated by Django 5.2.4 on 2025-07-04 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
        ('facturacion', '0003_lote_factura_lote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_resolucion', models.CharField(help_text='Número único de la resolución', max_length=50, unique=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True, help_text='Fecha en que se crea la resolución')),
                ('facturas', models.ManyToManyField(help_text='Facturas asociadas a esta resolución', related_name='resoluciones', to='facturacion.factura')),
                ('firmante', models.ForeignKey(blank=True, help_text='Persona que firma la resolución', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resoluciones_firmadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resolución',
                'verbose_name_plural': 'Resoluciones',
            },
        ),
    ]
