# Generated by Django 5.2.3 on 2025-06-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='glosa',
            name='archivo_soporte',
            field=models.FileField(blank=True, null=True, upload_to='glosas_soporte/'),
        ),
    ]
