# Generated by Django 5.2.3 on 2025-06-24 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_glosa_archivo_soporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glosa',
            name='archivo_soporte',
        ),
    ]
