# Generated by Django 5.2.4 on 2025-07-04 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_populate_catalogs'),
        ('auditoria', '0002_resolution'),
        ('facturacion', '0003_lote_factura_lote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número único de la resolución', max_length=50, unique=True)),
                ('fecha_creacion', models.DateField()),
                ('nombre_firmante', models.CharField(help_text='Nombre completo de la persona que firma la resolución', max_length=255)),
                ('firma_imagen', models.ImageField(blank=True, help_text='Imagen de la firma del responsable', null=True, upload_to='firmas_resoluciones/')),
                ('contenido_texto', models.TextField(blank=True, help_text='Contenido final de la resolución generada', null=True)),
                ('entidad_territorial_perfil', models.ForeignKey(help_text='Entidad Territorial que emite la resolución', limit_choices_to={'role': 'ET'}, on_delete=django.db.models.deletion.PROTECT, related_name='resoluciones_emitidas', to='accounts.profile')),
                ('facturas', models.ManyToManyField(help_text='Facturas que se incluyen en esta resolución', related_name='resoluciones', to='facturacion.factura')),
            ],
            options={
                'verbose_name': 'Resolución',
                'verbose_name_plural': 'Resoluciones',
            },
        ),
        migrations.DeleteModel(
            name='Resolution',
        ),
    ]
