# Generated by Django 5.2.3 on 2025-07-02 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0003_remove_glosa_archivo_soporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glosa',
            name='item',
        ),
    ]
