# Generated by Django 5.2.4 on 2025-07-04 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0003_resolucion_delete_resolution'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resolucion',
        ),
    ]
