# Generated by Django 5.2.3 on 2025-07-02 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0004_remove_glosa_item'),
        ('facturacion', '0003_contrato_paciente_factura_contrato_factura_paciente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glosa',
            name='consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.ripsconsulta'),
        ),
        migrations.AddField(
            model_name='glosa',
            name='hospitalizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.ripshospitalizacion'),
        ),
        migrations.AddField(
            model_name='glosa',
            name='medicamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.ripsmedicamento'),
        ),
        migrations.AddField(
            model_name='glosa',
            name='otro_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.ripsotroservicio'),
        ),
        migrations.AddField(
            model_name='glosa',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.paciente'),
        ),
        migrations.AddField(
            model_name='glosa',
            name='procedimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.ripsprocedimiento'),
        ),
    ]
