# Generated by Django 5.2.4 on 2025-07-08 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_direccion_profile_nit_and_more'),
        ('auditoria', '0004_delete_resolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='glosa',
            name='ips',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'IPS'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile'),
        ),
    ]
