# Generated by Django 5.2.4 on 2025-07-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0005_glosa_ips'),
    ]

    operations = [
        migrations.AddField(
            model_name='glosa',
            name='decision_et_justificacion',
            field=models.TextField(blank=True, help_text='Justificación de la decisión de la ET o motivo de la devolución.', null=True),
        ),
        migrations.AddField(
            model_name='glosa',
            name='fecha_decision_et',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='glosa',
            name='valor_aceptado_et',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor final de la glosa aceptado o levantado por la ET.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='glosa',
            name='aceptada',
            field=models.BooleanField(blank=True, help_text='Indica si la IPS aceptó la glosa (True) o la rechazó (False).', null=True),
        ),
        migrations.AlterField(
            model_name='glosa',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente de Respuesta IPS'), ('Respondida IPS', 'Respondida por IPS'), ('Aceptada ET', 'Aceptada por ET'), ('Rechazada ET', 'Rechazada por ET'), ('Devuelta a IPS', 'Devuelta a IPS (Reevaluación)'), ('Indefinida', 'Glosa Indefinida')], default='Pendiente', max_length=20),
        ),
    ]
