# Generated by Django 5.2.4 on 2025-07-10 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0006_glosa_decision_et_justificacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialGlosa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(choices=[('creada', 'Glosa Creada'), ('estado_cambiado', 'Estado Cambiado'), ('respondida_ips', 'Respondida por IPS'), ('decidida_et', 'Decidida por ET'), ('devuelta_ips', 'Devuelta a IPS'), ('archivo_adjuntado', 'Archivo Adjuntado'), ('valor_modificado', 'Valor Modificado'), ('justificacion_agregada', 'Justificación Agregada')], max_length=50)),
                ('estado_anterior', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_nuevo', models.CharField(blank=True, max_length=20, null=True)),
                ('valor_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_nuevo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('descripcion_cambio', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('glosa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='auditoria.glosa')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que realizó el cambio', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Glosa',
                'verbose_name_plural': 'Historial de Glosas',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
