# Generated by Django 5.2.4 on 2025-07-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0007_historialglosa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glosa',
            name='valor_aceptado_et',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor de la glosa que se descuenta del valor bruto. Si es 0, la glosa se levanta y no se descuenta.', max_digits=12, null=True),
        ),
    ]
