# Generated by Django 5.2.4 on 2025-07-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0008_alter_glosa_valor_aceptado_et'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoglosa',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tipoglosarespuestaips',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
    ]
