# Generated by Django 5.2.4 on 2025-07-17 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0009_alter_tipoglosa_codigo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='glosa',
            name='aceptada_segunda',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='glosa',
            name='archivo_soporte_respuesta_segunda',
            field=models.FileField(blank=True, null=True, upload_to='respuestas_glosas/'),
        ),
        migrations.AddField(
            model_name='glosa',
            name='decision_et_justificacion_segunda',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='glosa',
            name='descripcion_respuesta_segunda',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='glosa',
            name='fecha_decision_et_segunda',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='glosa',
            name='fecha_respuesta_segunda',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='glosa',
            name='pago_parcial',
            field=models.BooleanField(default=False, help_text='Indica si se aplica pago parcial'),
        ),
        migrations.AddField(
            model_name='glosa',
            name='subtipo_glosa_respuesta_et',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_et', to='auditoria.subtipoglosarespuestaips'),
        ),
        migrations.AddField(
            model_name='glosa',
            name='subtipo_glosa_respuesta_et_segunda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_segunda_et', to='auditoria.subtipoglosarespuestaips'),
        ),
        migrations.AddField(
            model_name='glosa',
            name='subtipo_glosa_respuesta_segunda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_segunda_ips', to='auditoria.subtipoglosarespuestaips'),
        ),
        migrations.AddField(
            model_name='glosa',
            name='tipo_glosa_respuesta_et',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_et', to='auditoria.tipoglosarespuestaips'),
        ),
        migrations.AddField(
            model_name='glosa',
            name='tipo_glosa_respuesta_et_segunda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_segunda_et', to='auditoria.tipoglosarespuestaips'),
        ),
        migrations.AddField(
            model_name='glosa',
            name='tipo_glosa_respuesta_segunda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_segunda_ips', to='auditoria.tipoglosarespuestaips'),
        ),
        migrations.AddField(
            model_name='glosa',
            name='valor_aceptado_et_segunda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='glosa',
            name='valor_parcial',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Nuevo valor cuando se aplica pago parcial', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='glosa',
            name='valor_parcial_segunda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='glosa',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente de Respuesta IPS'), ('Respondida IPS', 'Respondida por IPS'), ('Aceptada ET', 'Aceptada por ET'), ('Rechazada ET', 'Rechazada por ET'), ('Devuelta a IPS', 'Devuelta a IPS (Reevaluación)'), ('Respondida IPS Segunda', 'Segunda Respuesta de IPS'), ('Rechazada ET Segunda', 'Segunda Rechazo de ET'), ('En Conciliación', 'En Proceso de Conciliación'), ('Conciliada', 'Conciliada'), ('Indefinida', 'Glosa Indefinida')], default='Pendiente', max_length=30),
        ),
        migrations.AlterField(
            model_name='historialglosa',
            name='accion',
            field=models.CharField(choices=[('creada', 'Glosa Creada'), ('estado_cambiado', 'Estado Cambiado'), ('respondida_ips', 'Respondida por IPS'), ('decidida_et', 'Decidida por ET'), ('devuelta_ips', 'Devuelta a IPS'), ('archivo_adjuntado', 'Archivo Adjuntado'), ('valor_modificado', 'Valor Modificado'), ('justificacion_agregada', 'Justificación Agregada'), ('pago_parcial_activado', 'Pago Parcial Activado'), ('respuesta_segunda_ips', 'Segunda Respuesta de IPS'), ('decision_segunda_et', 'Segunda Decisión de ET'), ('conciliacion_iniciada', 'Conciliación Iniciada'), ('conciliacion_resuelta', 'Conciliación Resuelta')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historialglosa',
            name='estado_anterior',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historialglosa',
            name='estado_nuevo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Conciliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('documento_et', models.FileField(blank=True, null=True, upload_to='conciliaciones/')),
                ('respuesta_definitiva_et', models.TextField(blank=True, null=True)),
                ('valor_definitivo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente de Resolución'), ('Resuelta', 'Resuelta'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20)),
                ('glosa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conciliacion', to='auditoria.glosa')),
                ('iniciada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
