# Generated by Django 5.2.4 on 2025-07-18 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0010_glosa_aceptada_segunda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glosa',
            name='valor_parcial_et_primera',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor parcial establecido por ET en la primera decisión', max_digits=12, null=True),
        ),
    ]
