# Generated by Django 5.2.4 on 2025-07-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0011_glosa_valor_parcial_et_primera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialglosa',
            name='accion',
            field=models.CharField(choices=[('creada', 'Glosa Creada'), ('estado_cambiado', 'Estado Cambiado'), ('respondida_ips', 'Respondida por IPS'), ('decidida_et', 'Decidida por ET'), ('devuelta_ips', 'Devuelta a IPS'), ('archivo_adjuntado', 'Archivo Adjuntado'), ('valor_modificado', 'Valor Modificado'), ('justificacion_agregada', 'Justificación Agregada'), ('pago_parcial_activado', 'Pago Parcial Activado'), ('respuesta_segunda_ips', 'Segunda Respuesta de IPS'), ('decision_segunda_et', 'Segunda Decisión de ET'), ('conciliacion_iniciada', 'Conciliación Iniciada'), ('conciliacion_resuelta', 'Conciliación Resuelta'), ('valor_parcial_propuesto_ips', 'Valor Parcial Propuesto por IPS'), ('pago_parcial_activado_et', 'Pago Parcial Activado por ET')], max_length=50),
        ),
    ]
