# Generated by Django 5.2.4 on 2025-07-18 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0012_alter_historialglosa_accion'),
    ]

    operations = [
    ]
