# Generated by Django 5.2.3 on 2025-07-03 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaCartera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_glosado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado_pago', models.CharField(default='Pendiente', max_length=20)),
                ('eps', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_eps', to='accounts.profile')),
                ('factura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='facturacion.factura')),
                ('ips', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_ips', to='accounts.profile')),
            ],
        ),
    ]
