# Generated by Django 5.2.4 on 2025-07-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0002_alter_cuentacartera_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuentacartera',
            options={},
        ),
        migrations.RemoveField(
            model_name='cuentacartera',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='cuentacartera',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='cuentacartera',
            name='valor_glosado_definitivo',
        ),
        migrations.RemoveField(
            model_name='cuentacartera',
            name='valor_glosado_provisional',
        ),
        migrations.RemoveField(
            model_name='cuentacartera',
            name='valor_pagable',
        ),
        migrations.AlterField(
            model_name='cuentacartera',
            name='estado_pago',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='cuentacartera',
            name='valor_final',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cuentacartera',
            name='valor_glosado',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cuentacartera',
            name='valor_inicial',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
