# Generated by Django 5.2.4 on 2025-07-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0005_alter_cuentacartera_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuentacartera',
            options={'verbose_name': 'Cuenta de Cartera', 'verbose_name_plural': 'Cuentas de Cartera'},
        ),
        migrations.AddField(
            model_name='cuentacartera',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='cuentacartera',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cuentacartera',
            name='valor_glosado_definitivo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Valor total de glosas aceptadas definitivamente', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cuentacartera',
            name='valor_glosado_provisional',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Valor total de glosas pendientes/en proceso', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cuentacartera',
            name='valor_pagable',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor final a pagar (inicial - glosado_definitivo)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='cuentacartera',
            name='estado_pago',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Parcialmente_Glosado', 'Parcialmente Glosado'), ('Glosas_Pendientes', 'Glosas Pendientes'), ('Finalizado', 'Finalizado'), ('Pagado', 'Pagado')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='cuentacartera',
            name='valor_final',
            field=models.DecimalField(decimal_places=2, help_text='[LEGACY] Valor final', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cuentacartera',
            name='valor_glosado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='[LEGACY] Valor glosado total', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cuentacartera',
            name='valor_inicial',
            field=models.DecimalField(decimal_places=2, help_text='Valor bruto inicial de la factura', max_digits=12),
        ),
    ]
