# Generated by Django 5.2.4 on 2025-07-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0006_alter_cuentacartera_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentacartera',
            name='valor_final',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='[LEGACY] Valor final', max_digits=12, null=True),
        ),
    ]
