# Generated by Django 5.2.4 on 2025-07-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0007_alter_cuentacartera_valor_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentacartera',
            name='valor_final',
            field=models.DecimalField(decimal_places=2, default=100000, help_text='[LEGACY] Valor final', max_digits=12),
            preserve_default=False,
        ),
    ]
