# Generated by Django 5.0.6 on 2025-07-03 06:12

from django.db import migrations

def populate_catalogs(apps, schema_editor):
    CatalogoPais = apps.get_model('accounts', 'CatalogoPais')
    CatalogoMunicipio = apps.get_model('accounts', 'CatalogoMunicipio')
    CatalogoCUPS = apps.get_model('accounts', 'CatalogoCUPS')
    CatalogoCIE10 = apps.get_model('accounts', 'CatalogoCIE10')
    CatalogoCUMS = apps.get_model('accounts', 'CatalogoCUMS')

    # Datos para Pais (ejemplo)
    CatalogoPais.objects.bulk_create([
        CatalogoPais(codigo='170', nombre='COLOMBIA'),
    ])

    # Datos para Municipio (ejemplo)
    CatalogoMunicipio.objects.bulk_create([
        CatalogoMunicipio(codigo='50001', nombre='MEDELLIN'),
        CatalogoMunicipio(codigo='50002', nombre='BELLO'),
    ])

    # Datos para CUPS (ejemplo)
    CatalogoCUPS.objects.bulk_create([
        CatalogoCUPS(codigo='890202', descripcion='CONSULTA DE PRIMERA VEZ POR MEDICO GENERAL'),
        CatalogoCUPS(codigo='890302', descripcion='CONSULTA DE CONTROL O DE SEGUIMIENTO POR MEDICO GENERAL'),
    ])

    # Datos para CIE10 (ejemplo)
    CatalogoCIE10.objects.bulk_create([
        CatalogoCIE10(codigo='J00', descripcion='RINOFARINGITIS AGUDA (RESFRIADO COMUN)'),
        CatalogoCIE10(codigo='A09X', descripcion='DIARREA Y GASTROENTERITIS DE PRESUNTO ORIGEN INFECCIOSO'),
    ])
    
    # Datos para CUMS (ejemplo)
    CatalogoCUMS.objects.bulk_create([
        CatalogoCUMS(codigo='01', descripcion='CUMS DE PRUEBA 1'),
        CatalogoCUMS(codigo='02', descripcion='CUMS DE PRUEBA 2'),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_catalogs),
    ]
