# Generated by Django 5.2.3 on 2025-06-24 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('cufe', models.CharField(max_length=150)),
                ('fecha_emision', models.DateField()),
                ('fecha_radicacion', models.DateField(auto_now_add=True)),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado_auditoria', models.CharField(default='Radicada', max_length=20)),
                ('archivo_rips', models.FileField(upload_to='rips/')),
                ('eps', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_eps', to='accounts.Profile')),
                ('ips', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_ips', to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='RipsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(max_length=50)),
                ('paciente_id', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha', models.CharField(max_length=50)),
                ('diagnostico', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.factura')),
            ],
        ),
    ]
