# Generated by Django 5.2.3 on 2025-06-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ripsitem',
            name='cod_prestador',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
