# Generated by Django 5.2.3 on 2025-07-03 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='auditor',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'AUDITOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_auditadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
