# Generated by Django 5.2.3 on 2025-07-03 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_factura_auditor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre o código único para el lote', max_length=100, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente de Asignación'), ('Asignado', 'Asignado a Auditor'), ('En Auditoria', 'En Auditoría'), ('Auditado', 'Auditado'), ('Finalizado', 'Finalizado')], default='Pendiente', max_length=20)),
                ('auditor', models.ForeignKey(blank=True, help_text='Auditor asignado a este lote de facturas', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lote de Facturas',
                'verbose_name_plural': 'Lotes de Facturas',
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='lote',
            field=models.ForeignKey(blank=True, help_text='Lote al que pertenece esta factura', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='facturacion.lote'),
        ),
    ]
