# Generated by Django 5.2.3 on 2025-07-02 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_contrato_paciente_factura_contrato_factura_paciente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='tarifario',
        ),
        migrations.AddField(
            model_name='contrato',
            name='tarifario_adjunto',
            field=models.FileField(blank=True, help_text='Adjunto del tarifario general asociado a este contrato', null=True, upload_to='tarifarios/'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='adjunto',
            field=models.FileField(blank=True, help_text='Adjunto del contrato completo', null=True, upload_to='contratos/'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='alerta_vencimiento',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='condiciones_pago',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='servicios_cubiertos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TarifaContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_item', models.CharField(choices=[('CUPS', 'CUPS'), ('CUMS', 'CUMS'), ('SOAT', 'SOAT'), ('MANUAL', 'Manual')], max_length=20)),
                ('codigo_item', models.CharField(help_text='Código del CUPS, CUMS o servicio específico', max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_acordado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_vigencia_inicio', models.DateField(blank=True, null=True)),
                ('fecha_vigencia_fin', models.DateField(blank=True, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='facturacion.contrato')),
            ],
            options={
                'verbose_name': 'Tarifa de Contrato',
                'verbose_name_plural': 'Tarifas de Contrato',
                'unique_together': {('contrato', 'tipo_item', 'codigo_item')},
            },
        ),
    ]
