# Generated by Django 5.2.4 on 2025-07-04 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_lote_factura_lote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_resolucion', models.CharField(help_text='Número único de la resolución', max_length=50, unique=True)),
                ('entidad_territorial', models.CharField(help_text='Nombre de la Secretaría de Salud que emite la resolución', max_length=255)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('nombre_firmante', models.CharField(help_text='Nombre completo del firmante de la resolución', max_length=255)),
                ('cuerpo_resolucion_html', models.TextField(blank=True, help_text='Contenido HTML generado de la resolución', null=True)),
                ('archivo_pdf', models.FileField(blank=True, help_text='Archivo PDF de la resolución', null=True, upload_to='resoluciones_pdf/')),
                ('facturas', models.ManyToManyField(blank=True, help_text='Facturas aprobadas por esta resolución', related_name='resoluciones', to='facturacion.factura')),
            ],
            options={
                'verbose_name': 'Resolución',
                'verbose_name_plural': 'Resoluciones',
            },
        ),
    ]
