# Generated by Django 5.2.4 on 2025-07-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_resolucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualTarifario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(help_text='Referencia única del item tarifario', max_length=50, unique=True)),
                ('codigo', models.CharField(help_text='Código del CUPS, CUMS o servicio específico', max_length=50, unique=True)),
                ('descripcion', models.TextField(help_text='Descripción detallada del item')),
                ('uvr', models.DecimalField(decimal_places=2, help_text='Unidad de Valor Relativa (UVR)', max_digits=12)),
            ],
            options={
                'verbose_name': 'Manual Tarifario',
                'verbose_name_plural': 'Manuales Tarifarios',
            },
        ),
    ]
