# Generated by Django 5.2.4 on 2025-07-04 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_direccion_profile_nit_and_more'),
        ('facturacion', '0005_manualtarifario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='tipo',
        ),
        migrations.AddField(
            model_name='contrato',
            name='fecha_conciliacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fecha_liquidacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fecha_presupuesto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('10A - 30PP 60 sp', '10A - 30PP 60 sp')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='ips',
            field=models.ForeignKey(blank=True, help_text='IPS asociada a este contrato', limit_choices_to={'role': 'IPS'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_ips', to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='objeto',
            field=models.TextField(blank=True, help_text='Objeto o descripción del contrato', null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='supervisor',
            field=models.CharField(blank=True, help_text='Nombre del supervisor del contrato', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo_contrato',
            field=models.CharField(blank=True, choices=[('Contrato', 'Con Contrato'), ('Sin Contrato', 'Sin Contrato')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='vigencia',
            field=models.IntegerField(blank=True, help_text='Año de vigencia del contrato', null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
