# Generated by Django 5.2.4 on 2025-07-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0007_contrato_tipo_auditoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='tipo_auditoria',
        ),
        migrations.AddField(
            model_name='factura',
            name='tipo_auditoria',
            field=models.CharField(blank=True, choices=[('Acuerdo', 'Acuerdo'), ('Contrato', 'Contrato'), ('Ambulatorio', 'Ambulatorio'), ('Hospitalizacion', 'Hospitalización'), ('Urgencias', 'Urgencias')], help_text='Tipo de auditoría para la factura', max_length=20, null=True),
        ),
    ]
