# Generated by Django 5.2.4 on 2025-07-05 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0008_remove_contrato_tipo_auditoria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Código de Devolución',
                'verbose_name_plural': 'Códigos de Devolución',
            },
        ),
        migrations.CreateModel(
            name='UsuariosNoAptos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(help_text='Número de cédula del usuario no apto', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Nombre completo del usuario no apto', max_length=255)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Usuario No Apto',
                'verbose_name_plural': 'Usuarios No Aptos',
            },
        ),
        migrations.RemoveField(
            model_name='factura',
            name='estado_auditoria',
        ),
        migrations.AddField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('Radicada', 'Radicada'), ('Devuelta', 'Devuelta'), ('En Auditoria', 'En Auditoría'), ('Auditada', 'Auditada')], default='Radicada', max_length=20),
        ),
        migrations.CreateModel(
            name='SubcodigoDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcodigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.TextField()),
                ('codigo_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcodigos', to='facturacion.codigodevolucion')),
            ],
            options={
                'verbose_name': 'Subcódigo de Devolución',
                'verbose_name_plural': 'Subcódigos de Devolución',
            },
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_devolucion', models.DateTimeField(auto_now_add=True)),
                ('justificacion', models.TextField(blank=True, help_text='Justificación adicional para la devolución.', null=True)),
                ('devuelto_por', models.ForeignKey(blank=True, help_text='Usuario que registró la devolución (para devoluciones manuales)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('factura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='devolucion', to='facturacion.factura')),
                ('subcodigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.subcodigodevolucion')),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
            },
        ),
    ]
