# Generated by Django 5.2.4 on 2025-07-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0010_populate_devolucion_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='archivo_pdf',
            field=models.FileField(blank=True, help_text='Archivo PDF de la factura', null=True, upload_to='facturas_pdf/'),
        ),
    ]
