# Generated by Django 5.2.4 on 2025-07-11 01:36

import uuid
from django.db import migrations, models


def generate_uuids_for_existing_facturas(apps, schema_editor):
    """Genera UUIDs únicos para todas las facturas existentes"""
    Factura = apps.get_model('facturacion', 'Factura')
    for factura in Factura.objects.all():
        factura.codigo_uuid = uuid.uuid4()
        factura.save()


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0011_factura_archivo_pdf'),
    ]

    operations = [
        # Primero agregar el campo sin restricción unique
        migrations.AddField(
            model_name='factura',
            name='codigo_uuid',
            field=models.UUIDField(null=True, blank=True, help_text='Código único automático de la factura'),
        ),
        
        # Generar UUIDs para facturas existentes
        migrations.RunPython(generate_uuids_for_existing_facturas, reverse_code=migrations.RunPython.noop),
        
        # Hacer el campo no nullable y con default
        migrations.AlterField(
            model_name='factura',
            name='codigo_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Código único automático de la factura'),
        ),
        
        # Agregar restricción unique
        migrations.AlterField(
            model_name='factura',
            name='codigo_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Código único automático de la factura', unique=True),
        ),
    ]
