# Generated by Django 5.2.4 on 2025-07-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0012_add_uuid_field_with_data_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariosnoaptos',
            name='codigo_eps',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuariosnoaptos',
            name='codigo_ips_primaria',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuariosnoaptos',
            name='condicion_beneficiario',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuariosnoaptos',
            name='departamento_residencia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuariosnoaptos',
            name='estado_afiliacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuariosnoaptos',
            name='fecha_afiliacion_sgsss',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuariosnoaptos',
            name='fecha_inicio_afiliacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuariosnoaptos',
            name='fecha_inicio_condicion_afiliacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuariosnoaptos',
            name='fecha_inicio_ultimo_tramo_condicion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuariosnoaptos',
            name='fecha_nacimiento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuariosnoaptos',
            name='ficha_sisben',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuariosnoaptos',
            name='genero',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuariosnoaptos',
            name='grupo_poblacional',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuariosnoaptos',
            name='metodologia_grupo_poblacional',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuariosnoaptos',
            name='modalidad_subsidio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuariosnoaptos',
            name='municipio_residencia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuariosnoaptos',
            name='nivel_sisben_iii',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuariosnoaptos',
            name='nivel_sisben_iii_iv_listados',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuariosnoaptos',
            name='nivel_sisben_iv',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuariosnoaptos',
            name='numero_documento_afiliado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuariosnoaptos',
            name='pais_residencia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuariosnoaptos',
            name='parentesco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuariosnoaptos',
            name='portabilidad_afiliado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuariosnoaptos',
            name='primer_apellido_afiliado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuariosnoaptos',
            name='primer_nombre_afiliado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuariosnoaptos',
            name='segundo_apellido_afiliado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuariosnoaptos',
            name='segundo_nombre_afiliado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuariosnoaptos',
            name='serial_bdua_cotizante',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuariosnoaptos',
            name='tipo_afiliado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuariosnoaptos',
            name='tipo_documento_afiliado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuariosnoaptos',
            name='tipo_documento_cotizante',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuariosnoaptos',
            name='tipologia_especial',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuariosnoaptos',
            name='zona_afiliacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usuariosnoaptos',
            name='cedula',
            field=models.CharField(help_text='Número de cédula del usuario no apto', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='usuariosnoaptos',
            name='fecha_registro',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usuariosnoaptos',
            name='nombre',
            field=models.CharField(help_text='Nombre completo del usuario no apto', max_length=200),
        ),
    ]
