# Generated by Django 5.2.4 on 2025-07-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0013_usuariosnoaptos_codigo_eps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosnoaptos',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
