# Generated by Django 5.2.4 on 2025-07-17 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0014_alter_usuariosnoaptos_fecha_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariosnoaptos',
            name='codigo_ips_primaria',
        ),
        migrations.RemoveField(
            model_name='usuariosnoaptos',
            name='condicion_beneficiario',
        ),
        migrations.RemoveField(
            model_name='usuariosnoaptos',
            name='departamento_residencia',
        ),
        migrations.RemoveField(
            model_name='usuariosnoaptos',
            name='estado_afiliacion',
        ),
        migrations.RemoveField(
            model_name='usuariosnoaptos',
            name='fecha_afiliacion_sgsss',
        ),
        migrations.RemoveField(
            model_name='usuariosnoaptos',
            name='fecha_inicio_afiliacion',
        ),
        migrations.RemoveField(
            model_name='usuariosnoaptos',
            name='fecha_inicio_condicion_afiliacion',
        ),
        migrations.RemoveField(
            model_name='usuariosnoaptos',
            name='fecha_inicio_ultimo_tramo_condicion',
        ),
        migrations.RemoveField(
            model_name='usuariosnoaptos',
            name='ficha_sisben',
        ),
        migrations.RemoveField(
            model_name='usuariosnoaptos',
            name='grupo_poblacional',
        ),
        migrations.RemoveField(
            model_name='usuariosnoaptos',
            name='metodologia_grupo_poblacional',
        ),
        migrations.RemoveField(
            model_name='usuariosnoaptos',
            name='modalidad_subsidio',
        ),
        migrations.RemoveField(
            model_name='usuariosnoaptos',
            name='municipio_residencia',
        ),
        migrations.RemoveField(
            model_name='usuariosnoaptos',
            name='nivel_sisben_iii',
        ),
        migrations.RemoveField(
            model_name='usuariosnoaptos',
            name='nivel_sisben_iii_iv_listados',
        ),
        migrations.RemoveField(
            model_name='usuariosnoaptos',
            name='nivel_sisben_iv',
        ),
        migrations.RemoveField(
            model_name='usuariosnoaptos',
            name='parentesco',
        ),
        migrations.RemoveField(
            model_name='usuariosnoaptos',
            name='portabilidad_afiliado',
        ),
        migrations.RemoveField(
            model_name='usuariosnoaptos',
            name='serial_bdua_cotizante',
        ),
        migrations.RemoveField(
            model_name='usuariosnoaptos',
            name='tipo_afiliado',
        ),
        migrations.RemoveField(
            model_name='usuariosnoaptos',
            name='tipologia_especial',
        ),
        migrations.RemoveField(
            model_name='usuariosnoaptos',
            name='zona_afiliacion',
        ),
    ]
