# Generated by Django 5.2.4 on 2025-07-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0015_remove_usuariosnoaptos_codigo_ips_primaria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosnoaptos',
            name='cedula',
            field=models.CharField(help_text='Número de cédula del usuario no apto', max_length=200),
        ),
    ]
